// <auto-generated/>
using Microsoft.AspNetCore.Hosting;

[assembly: HostingStartup(typeof(DinosaursShop.Areas.Identity.IdentityHostingStartup))]
namespace DinosaursShop.Areas.Identity
{
    public class IdentityHostingStartup : IHostingStartup
    {
        public void Configure(IWebHostBuilder builder)
        {
            builder.ConfigureServices((context, services) => {
            });
        }
    }
}