// <auto-generated />
using DinosaursShop.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DinosaursShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DinosaursShop.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryDescription = "Meat eating dinosaur",
                            CategoryName = "Carnivornes"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryDescription = "Plant eating dinosaur",
                            CategoryName = "Herbivores"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryDescription = "Meat and plants eating dinosaur",
                            CategoryName = "Omnivores"
                        });
                });

            modelBuilder.Entity("DinosaursShop.Models.Dinosaur", b =>
                {
                    b.Property<int>("DinosaurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsInStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnSale")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DinosaurId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Dinosaurs");

                    b.HasData(
                        new
                        {
                            DinosaurId = 1,
                            CategoryId = 1,
                            Description = "Allosaurus was a typical large theropod, having a massive skull on a short neck, a long, slightly sloping tail and reduced forelimbs. Allosaurus fragilis, the best-known species, had an average length of 8.5 m (28 ft), with the largest definitive Allosaurus specimen estimated at 9.7 meters (32 feet) long, and an estimated weight of 2.3 metric tons (2.5 short tons).",
                            ImageThumbnailUrl = "/images/thumbnails/Allosaurus_Juvenile_Reconstruction.jpg",
                            ImageUrl = "/images/Allosaurus_Juvenile_Reconstruction.jpg",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Allosaurus",
                            Price = 1500m
                        },
                        new
                        {
                            DinosaurId = 2,
                            CategoryId = 3,
                            Description = "Nomingia is a medium-sized oviraptorosaur to have been 1.7 metres (5.6 ft) long and 20 kilograms (44 lb) in weight. It is characterized by a pygostyle-like mass of five fused vertebrae at the tail end.",
                            ImageThumbnailUrl = "/images/thumbnails/220px-Nomingia_gobiensis.png",
                            ImageUrl = "/images/800px-Nomingia_gobiensis.png.jpg",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Nomingia",
                            Price = 950m
                        },
                        new
                        {
                            DinosaurId = 3,
                            CategoryId = 1,
                            Description = "Velociraptor was a mid-sized dromaeosaurid, with adults measuring up to 2.07 m (6 ft 9 1⁄2 in) long, 0.5 m (1 ft 7 1⁄2 in) high at the hip, and weighing up to 15 kg (33 lb), though there is a higher estimate of 19.7 kg (43 1⁄2 lb). The skull, which grew up to 25 cm (10 in) long, is uniquely up-curved, concave on the upper surface and convex on the lower. The jaws is lined with 26–28 widely spaced teeth on each side, each more strongly serrated on the back edge than the front",
                            ImageThumbnailUrl = "/images/thumbnails/220px-Velociraptor_Restoration.png",
                            ImageUrl = "/images/1024px-Velociraptor_Restoration.png",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Velociraptor",
                            Price = 1000m
                        },
                        new
                        {
                            DinosaurId = 4,
                            CategoryId = 3,
                            Description = "Eoraptor has a slender body that grew to about 1 metre (3 ft 3 in) in length, with an estimated weight of about 10 kilograms (22 lb). It has a lightly built skull with a slightly enlarged external naris.",
                            ImageThumbnailUrl = "/images/thumbnails/220px-Eoraptor_NT_small.jpg",
                            ImageUrl = "/images/Eoraptor_NT_small.jpg",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Eoraptor",
                            Price = 500m
                        },
                        new
                        {
                            DinosaurId = 5,
                            CategoryId = 2,
                            Description = "Individual Triceratops are estimated to have reached about 7.9 to 9 metres (26 to 30 ft) in length, 2.9 to 3.0 m (9.5 to 9.8 ft) in height, and 6.1 to 12.0 tonnes (13,400 to 26,500 lb) in weight. The most distinctive feature is their large skull, among the largest of all land animals.",
                            ImageThumbnailUrl = "/images/thumbnails/220px-Knight_Triceratops.jpg",
                            ImageUrl = "/images/Knight_Triceratops.jpg",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Triceratops",
                            Price = 1500m
                        },
                        new
                        {
                            DinosaurId = 6,
                            CategoryId = 2,
                            Description = "Over the years, the mass of B. altithorax has been estimated at 35.0 metric tons (38.6 short tons),28.3 metric tons (31.2 short tons), 43.9 metric tons (48.4 short tons), 28.7 metric tons (31.6 short tons), 56.3 metric tons (62.1 short tons), and 58 metric tons (64 short tons). The length of Brachiosaurus has been estimated at 20–21 meters (66–69 ft) and 18 meters (59 ft), and its height at 9.4 meters (30 3⁄4 ft) and 12–13 meters (39–43 ft).",
                            ImageThumbnailUrl = "/images/thumbnails/220px-Brachiosaurus_NT_new.jpg",
                            ImageUrl = "/images/Brachiosaurus_NT_new.jpg",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Brachiosaurus",
                            Price = 2500m
                        });
                });

            modelBuilder.Entity("DinosaursShop.Models.Dinosaur", b =>
                {
                    b.HasOne("DinosaursShop.Models.Category", "Category")
                        .WithMany("Dinosaurs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
